Repository lanis-mobile/lanis, pull requests merged in 2023-12, with the labels that each got.

#28 Support für "Nachrichten Beta-Version" hinzufügen
  app/lib/client/client.dart
  app/lib/client/cryptor.dart
  app/lib/main.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/conversations/detailed_conversation.dart
  app/lib/view/settings/subsettings/supported_features.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#31 Fix cryptor not using same client
  app/lib/client/client.dart
  app/lib/client/cryptor.dart
Labels: bug

#32 Mein unterricht
  app/lib/client/client.dart
  app/lib/client/cryptor.dart
  app/lib/client/storage.dart
  app/lib/main.dart
  app/lib/view/conversations/detailed_conversation.dart
  app/lib/view/mein_unterricht/.gitkeep
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
  app/pubspec.lock
Labels: enhancement

#33 Refreshing and faster conversations.
  app/lib/client/client.dart
  app/lib/view/conversations/conversations.dart
Labels: enhancement

#35 Fix calendar
  app/lib/client/client.dart
  app/lib/view/calendar/calendar.dart
Labels: bug, enhancement

#36 Some more bugs
  app/lib/client/client.dart
  app/lib/main.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/conversations/detailed_conversation.dart
  app/lib/view/settings/subsettings/user_login.dart
  app/lib/view/settings/subsettings/userdata.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: bug

#38 Add "Nachrichten Beta-Version" screenshots.
  README.md
  screenshots/Conversation_Details.png
  screenshots/Conversations_Overview.png
Labels: documentation

#39 bug-reports
  app/lib/background_service/service.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/send_bugreport.dart
  app/pubspec.lock
  app/pubspec.yaml
  bugreport/client/sph-bugreport-frontend/.gitignore
  bugreport/client/sph-bugreport-frontend/index.html
  bugreport/client/sph-bugreport-frontend/main.js
  bugreport/client/sph-bugreport-frontend/package-lock.json
  bugreport/client/sph-bugreport-frontend/package.json
  bugreport/client/sph-bugreport-frontend/style.css
  bugreport/server/.gitignore
  bugreport/server/package-lock.json
  bugreport/server/package.json
  bugreport/server/schema.sql
  bugreport/server/src/index.ts
  bugreport/server/tsconfig.json
  bugreport/server/wrangler.toml
  icon.xcf
Labels: enhancement

#47 New drawer and login
  app/lib/client/client.dart
  app/lib/main.dart
  app/lib/themes/dark_theme.dart
  app/lib/themes/light_theme.dart
  app/lib/view/bug_report/send_bugreport.dart
  app/lib/view/settings/settings.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#50 set app name and icon. update readme
  README.md
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/drawable-mdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/drawable-xhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/drawable-xxhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/assets/icon.png
  app/lib/background_service/service.dart
  app/lib/main.dart
  app/lib/view/settings/subsettings/user_login.dart
Labels: enhancement

#51 Calendar fix
  README.md
  app/lib/main.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/settings/subsettings/about.dart
  bugreport/server/src/index.ts
Labels: bug, enhancement

#54 Notification icon
  app/android/app/src/main/res/drawable-hdpi/ic_launcher.png
  app/android/app/src/main/res/drawable-mdpi/ic_launcher.png
  app/android/app/src/main/res/drawable-xhdpi/ic_launcher.png
  app/android/app/src/main/res/drawable-xxhdpi/ic_launcher.png
  app/android/app/src/main/res/drawable-xxxhdpi/ic_launcher.png
  app/lib/background_service/service.dart
Labels: enhancement

#58 initial fastlane structure
  fastlane/metadata/android/de/full_description.txt
  fastlane/metadata/android/de/short_description.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/01.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/02.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/03.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/04.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/05.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/06.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/07.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/08.png
  fastlane/metadata/android/en-US/short_description.txt
Labels: todo

#60 Fix substitutions not supported
  app/lib/main.dart
Labels: bug

#59 Cache data
  app/lib/client/client.dart
  app/lib/client/fetcher.dart
  app/lib/main.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/load_mode.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#62 Fix no network login
  app/lib/client/client.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: bug

#73 fix #70
  app/lib/client/client.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
Labels: bug

#74 fix login fetchers not initialized.
  app/lib/client/client.dart
  app/lib/main.dart
Labels: bug

#64 Improve vp
  app/lib/background_service/service.dart
  app/lib/client/client.dart
  app/lib/client/fetcher.dart
  app/lib/main.dart
  app/lib/shared/errorView.dart
  app/lib/shared/shared_functions.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: enhancement

#88 Calendar improvements
  app/lib/client/client.dart
  app/lib/shared/errorView.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: enhancement

#92 Add no entries view for vp
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: enhancement

#91 Countly
  README.md
  app/android/build.gradle
  app/lib/client/client.dart
  app/lib/firebase_options.dart
  app/lib/main.dart
  app/lib/shared/shared_functions.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#89 Conversations improvement
  app/fonts/RobotoMono-Regular.ttf
  app/lib/client/client.dart
  app/lib/shared/errorView.dart
  app/lib/shared/shared_functions.dart
  app/lib/shared/styledTextWidget.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/conversations/detailed_conversation.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#95 Better login screen
  app/assets/school_list.json
  app/assets/undraw/undraw_access_account_re_8spm.svg
  app/assets/undraw/undraw_active_options_re_8rj3.svg
  app/assets/undraw/undraw_add_color_re_buro.svg
  app/assets/undraw/undraw_bug_fixing_oc-7-a.svg
  app/assets/undraw/undraw_building_blocks_re_5ahy.svg
  app/assets/undraw/undraw_content_re_33px.svg
  app/assets/undraw/undraw_editable_re_4l94.svg
  app/assets/undraw/undraw_engineering_team_a7n2.svg
  app/assets/undraw/undraw_filter_re_sa16.svg
  app/assets/undraw/undraw_new_notifications_re_xpcv.svg
  app/assets/undraw/undraw_profile_re_4a55.svg
  app/assets/undraw/undraw_settings_re_b08x.svg
  app/assets/undraw/undraw_speed_test_re_pe1f.svg
  app/assets/undraw/undraw_welcome_re_h3d9.svg
  app/assets/undraw/undraw_wireframing_re_q6k6.svg
  app/lib/client/client.dart
  app/lib/main.dart
  app/lib/view/login/auth.dart
  app/lib/view/login/intro_screen_page_view_models.dart
  app/lib/view/login/screen.dart
  app/lib/view/login/setup_screen_page_view_models.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/about.dart
  app/lib/view/settings/subsettings/load_mode.dart
  app/lib/view/settings/subsettings/notifications.dart
  app/lib/view/settings/subsettings/theme_changer.dart
  app/lib/view/settings/subsettings/user_login.dart
  app/lib/view/vertretungsplan/filtersettings.dart
  app/lib/view/vertretungsplan/substitutionWidget.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
  app/pubspec.lock
  app/pubspec.yaml
  format_school_list.js
Labels: enhancement

#99 Proprietary components
  app/android/app/google-services.json
  app/android/app/src/main/AndroidManifest.xml
  app/lib/main.dart
  app/lib/view/login/auth.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/countly_analysis.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#100 Update README.md
  README.md
Labels: enhancement

#98 Mein Unterricht improvements
  app/lib/client/client.dart
  app/lib/shared/errorView.dart
  app/lib/shared/format_text.dart
  app/lib/shared/styledTextWidget.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/conversations/detailed_conversation.dart
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement
