Repository lanis-mobile/lanis, pull requests merged in 2024-09, with the labels that each got.

#248 Add moodle webview
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/res/values-night-v31/styles.xml
  app/android/app/src/main/res/values-night/styles.xml
  app/android/app/src/main/res/values-v31/styles.xml
  app/android/app/src/main/res/values/styles.xml
  app/lib/client/client.dart
  app/lib/home_page.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/shared/launch_file.dart
  app/lib/shared/widgets/error_view.dart
  app/lib/view/moodle.dart
  app/pubspec.yaml
Labels: enhancement

#257 Add new school selection system
  app/assets/school_list.json
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/startup.dart
  app/lib/view/login/auth.dart
  app/lib/view/login/school_selector.dart
  app/pubspec.yaml
Labels: enhancement

#259 timetable enhancement
  app/lib/client/client_submodules/timetable.dart
  app/lib/client/fetcher.dart
  app/lib/client/storage.dart
  app/lib/shared/types/timetable.dart
  app/lib/startup.dart
  app/lib/view/substitutions/view.dart
  app/lib/view/timetable/view.dart
Labels: enhancement, help wanted

#270 Add Tooltips for Timetable Buttons
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/view/timetable/view.dart
Labels: enhancement

#269 Login into Lanis instead of setting cookies.
  app/android/app/src/main/AndroidManifest.xml
  app/lib/client/client.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/view/moodle.dart
  app/pubspec.yaml
Labels: bug, enhancement

#272 267-auto-cache-clear
  app/lib/client/client.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/shared/launch_file.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/cache.dart
  app/pubspec.yaml
Labels: enhancement, datenschutz

#273 Improve main "mein_unterricht" page by adding data types and refreshing the code UI
  app/lib/client/client_submodules/mein_unterricht.dart
  app/lib/client/fetcher.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/shared/types/lesson.dart
  app/lib/view/mein_unterricht/attendances.dart
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/mein_unterricht/homework_box.dart
  app/lib/view/mein_unterricht/lesson_list_tile.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
Labels: enhancement

#278 Update info enhancement
  app/lib/home_page.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/shared/widgets/whats_new.dart
  app/lib/startup.dart
Labels: enhancement, low priority
