Repository lanis-mobile/lanis, pull requests merged in 2024-08, with the labels that each got.

#218 Nachrichten - Rework
  app/lib/client/client_submodules/conversations.dart
  app/lib/home_page.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/main.dart
  app/lib/shared/types/conversations.dart
  app/lib/shared/unicode.dart
  app/lib/shared/widgets/error_view.dart
  app/lib/shared/widgets/format_text.dart
  app/lib/startup.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/conversations/chat.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/conversations/detailed_conversation.dart
  app/lib/view/conversations/overview.dart
  app/lib/view/conversations/send.dart
  app/lib/view/conversations/shared.dart
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/mein_unterricht/upload_page.dart
  app/lib/view/substitutions/view.dart
  app/lib/view/timetable/view.dart
  app/pubspec.yaml
Labels: enhancement

#235 234 ios background service
  .DS_Store
  app/ios/Podfile
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  app/ios/Runner/AppDelegate.swift
  app/ios/Runner/Info.plist
  app/lib/background_service.dart
  app/lib/home_page.dart
  app/lib/l10n/app_en.arb
  app/lib/main.dart
  app/lib/view/data_storage/node_view.dart
  app/lib/view/data_storage/root_view.dart
  app/lib/view/login/setup_screen_page_view_models.dart
  app/lib/view/settings/subsettings/notifications.dart
  app/pubspec.yaml
Labels: enhancement, iOS

#246 fix: unable to create filters on some devices
  app/android/app/build.gradle
  app/android/app/proguard-rules.pro
  app/lib/client/client_submodules/mein_unterricht.dart
  app/lib/shared/widgets/whats_new.dart
  app/lib/view/substitutions/chips_input.dart
  app/lib/view/substitutions/filtersettings.dart
Labels: bug
