Repository lanis-mobile/lanis, pull requests merged in 2024-05, with the labels that each got.

#219 Startup cleanup
  app/assets/startup.svg
  app/lib/client/client_submodules/substitutions.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/startup.dart
  app/pubspec.yaml
Labels: enhancement

#220 Improve login screen and remove startup render overflow
  app/lib/background_service.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/view/login/auth.dart
  app/lib/view/login/screen.dart
  format_school_list.js
Labels: bug, enhancement

#223 fix #216
  app/lib/shared/widgets/substitutions/substitutions_gridtile.dart
  app/lib/shared/widgets/substitutions/substitutions_listtile.dart
Labels: bug, enhancement, low priority

#224 optimize network usage with custom network checking implementation
  app/lib/client/client.dart
  app/lib/client/client_submodules/calendar.dart
  app/lib/client/client_submodules/conversations.dart
  app/lib/client/connection_checker.dart
  app/lib/client/fetcher.dart
  app/lib/home_page.dart
  app/pubspec.yaml
Labels: enhancement, todo

#225 fix: show errorView in substitutions
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/shared/widgets/error_view.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: bug, enhancement

#227 Call dispose properly in entire project
  app/lib/shared/types/startup_app.dart
  app/lib/startup.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/data_storage/root_view.dart
  app/lib/view/login/auth.dart
  app/lib/view/mein_unterricht/upload_page.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: enhancement
