Repository lanis-mobile/lanis, pull requests merged in 2024-10, with the labels that each got.

#274 Configure settings through environment variables.
  app/lib/client/client.dart
  app/lib/client/storage.dart
  app/lib/main.dart
  app/lib/view/settings/subsettings/theme_changer.dart
  app/template_config.json
Labels: enhancement

#281 fix: timetable
  app/lib/client/client_submodules/timetable.dart
  app/lib/main.dart
  app/lib/shared/types/fach.dart
  app/lib/view/timetable/view.dart
Labels: bug

#285 fix: Proxy on iOS devices
  app/android/build.gradle
  app/lib/main.dart
  app/pubspec.yaml
Labels: bug, iOS

#283 calendar: add search and data class + cleanup
  app/lib/client/client_submodules/calendar.dart
  app/lib/client/fetcher.dart
  app/lib/shared/keyboard_observer.dart
  app/lib/shared/types/calendar_event.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/data_storage/root_view.dart
  app/lib/view/timetable/view.dart
Labels: enhancement

#253 Refactor conversation overview
  app/lib/client/client_submodules/conversations.dart
  app/lib/client/fetcher.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/shared/types/conversations.dart
  app/lib/view/conversations/chat.dart
  app/lib/view/conversations/overview.dart
  app/lib/view/conversations/overview_dialogs.dart
  app/lib/view/conversations/send.dart
Labels: enhancement
