Repository lanis-mobile/lanis, pull requests merged in 2024-03, with the labels that each got.

#191 make substitutions view a gridview and fix image providers
  app/lib/background_service/service.dart
  app/lib/client/client.dart
  app/lib/client/client_submodules/calendar.dart
  app/lib/client/client_submodules/conversations.dart
  app/lib/client/client_submodules/datastorage.dart
  app/lib/client/client_submodules/mein_unterricht.dart
  app/lib/client/client_submodules/substitutions.dart
  app/lib/client/client_submodules/timetable.dart
  app/lib/client/connection_checker.dart
  app/lib/client/fetcher.dart
  app/lib/client/storage.dart
  app/lib/home_page.dart
  app/lib/main.dart
  app/lib/shared/account_types.dart
  app/lib/shared/apps.dart
  app/lib/shared/exceptions/client_status_exceptions.dart
  app/lib/shared/types/dateispeicher_node.dart
  app/lib/shared/types/fach.dart
  app/lib/shared/types/startup_app.dart
  app/lib/shared/types/upload.dart
  app/lib/shared/unicode.dart
  app/lib/shared/whats_new.dart
  app/lib/shared/widgets/error_view.dart
  app/lib/shared/widgets/format_text.dart
  app/lib/shared/widgets/marquee.dart
  app/lib/shared/widgets/substitutions/substitutions_gridtile.dart
  app/lib/shared/widgets/substitutions/substitutions_listtile.dart
  app/lib/shared/widgets/whats_new.dart
  app/lib/startup.dart
  app/lib/themes.dart
  app/lib/view/bug_report/send_bugreport.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/conversations/detailed_conversation.dart
  app/lib/view/login/auth.dart
  app/lib/view/login/intro_screen_page_view_models.dart
  app/lib/view/login/screen.dart
  app/lib/view/login/setup_screen_page_view_models.dart
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/mein_unterricht/upload_page.dart
  app/lib/view/settings/info_button.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/about.dart
  app/lib/view/settings/subsettings/clear_cache.dart
  app/lib/view/settings/subsettings/countly_analysis.dart
  app/lib/view/settings/subsettings/load_mode.dart
  app/lib/view/settings/subsettings/notifications.dart
  app/lib/view/settings/subsettings/start_apps.dart
  app/lib/view/settings/subsettings/supported_features.dart
  app/lib/view/settings/subsettings/theme_changer.dart
  app/lib/view/settings/subsettings/userdata.dart
  app/lib/view/vertretungsplan/filterlogic.dart
  app/lib/view/vertretungsplan/filtersettings.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement, todo

#192 Fix conversation lag on loading
  app/lib/client/client_submodules/conversations.dart
  app/lib/client/cryptor.dart
  app/lib/client/fetcher.dart
  app/lib/home_page.dart
Labels: bug

#196 Dateispeicher Browser
  app/lib/client/client.dart
  app/lib/client/client_submodules/datastorage.dart
  app/lib/client/client_submodules/substitutions.dart
  app/lib/home_page.dart
  app/lib/shared/launch_file.dart
  app/lib/shared/types/dateispeicher_node.dart
  app/lib/view/data_storage/data_storage.dart
  app/lib/view/data_storage/file_listtile.dart
  app/lib/view/data_storage/folder_listtile.dart
  app/lib/view/data_storage/node_view.dart
  app/lib/view/data_storage/root_view.dart
  app/lib/view/login/auth.dart
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/settings/subsettings/clear_cache.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#199 fix: downloading not working in "mein unterricht"
  app/lib/shared/launch_file.dart
  app/lib/view/mein_unterricht/course_overview.dart
Labels: bug

#203 Feat: Show comments on Marks
  app/lib/client/client_submodules/mein_unterricht.dart
  app/lib/view/mein_unterricht/course_overview.dart
Labels: enhancement

#206 Feat: Better error handling in loading screen
  app/lib/client/client.dart
  app/lib/shared/exceptions/client_status_exceptions.dart
  app/lib/startup.dart
  app/lib/view/login/auth.dart
Labels: enhancement

#207 Timetable UI
  app/lib/client/client.dart
  app/lib/client/client_submodules/timetable.dart
  app/lib/client/fetcher.dart
  app/lib/home_page.dart
  app/lib/shared/types/fach.dart
  app/lib/view/timetable/timetable.dart
  app/pubspec.yaml
Labels: enhancement

#210 Simplify fetcher saving
  app/lib/client/client.dart
  app/lib/client/client_submodules/conversations.dart
  app/lib/client/client_submodules/datastorage.dart
  app/lib/client/cryptor.dart
  app/lib/client/fetcher.dart
  app/lib/client/storage.dart
  app/lib/home_page.dart
  app/lib/shared/apps.dart
  app/lib/shared/launch_file.dart
  app/lib/shared/types/dateispeicher_node.dart
  app/lib/shared/types/startup_app.dart
  app/lib/shared/widgets/error_view.dart
  app/lib/startup.dart
  app/lib/view/bug_report/send_bugreport.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/data_storage/data_storage.dart
  app/lib/view/data_storage/file_listtile.dart
  app/lib/view/data_storage/folder_listtile.dart
  app/lib/view/data_storage/node_view.dart
  app/lib/view/data_storage/root_view.dart
  app/lib/view/login/setup_screen_page_view_models.dart
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/settings/info_button.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/start_apps.dart
  app/lib/view/timetable/timetable.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
  bugreport/client/sph-bugreport-frontend/.gitignore
  bugreport/client/sph-bugreport-frontend/index.html
  bugreport/client/sph-bugreport-frontend/main.js
  bugreport/client/sph-bugreport-frontend/package-lock.json
  bugreport/client/sph-bugreport-frontend/package.json
  bugreport/client/sph-bugreport-frontend/style.css
  bugreport/server/.gitignore
  bugreport/server/package-lock.json
  bugreport/server/package.json
  bugreport/server/schema.sql
  bugreport/server/src/index.ts
  bugreport/server/tsconfig.json
  bugreport/server/wrangler.toml
Labels: enhancement
