Repository lanis-mobile/lanis, pull requests merged in 2024-02, with the labels that each got.

#155 Exceptions statt Status-Codes
  app/lib/background_service/service.dart
  app/lib/client/client.dart
  app/lib/client/fetcher.dart
  app/lib/main.dart
  app/lib/shared/exceptions/client_status_exceptions.dart
  app/lib/view/login/auth.dart
Labels: enhancement

#161 Handle storage keys and defaults globaly
  app/lib/background_service/service.dart
  app/lib/client/client.dart
  app/lib/client/storage.dart
  app/lib/main.dart
  app/lib/shared/whats_new.dart
  app/lib/themes.dart
  app/lib/view/login/auth.dart
  app/lib/view/settings/subsettings/countly_analysis.dart
  app/lib/view/settings/subsettings/load_mode.dart
  app/lib/view/settings/subsettings/notifications.dart
  app/lib/view/vertretungsplan/filterlogic.dart
Labels: enhancement

#170 Add button to show 1st halbjahr if possible
  app/lib/client/client_submodules/mein_unterricht.dart
  app/lib/view/mein_unterricht/course_overview.dart
Labels: bug, enhancement

#171 Modul-Enum optimieren und Support-Status erweitern
  app/lib/shared/apps.dart
  app/lib/view/settings/subsettings/supported_features.dart
Labels: enhancement

#172 Exceptions weiter
  app/lib/client/client.dart
  app/lib/client/client_submodules/conversations.dart
  app/lib/client/client_submodules/mein_unterricht.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/mein_unterricht/upload_page.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: enhancement

#173 Fix: Auth screen not showing up on first launch
  app/lib/client/client.dart
  app/lib/client/storage.dart
  app/lib/main.dart
Labels: bug

#177 sph connection check
  app/lib/client/client.dart
  app/lib/client/client_submodules/calendar.dart
  app/lib/client/client_submodules/conversations.dart
  app/lib/client/client_submodules/mein_unterricht.dart
  app/lib/client/client_submodules/substitutions.dart
  app/lib/client/connection_checker.dart
  app/lib/client/fetcher.dart
  app/lib/main.dart
  app/lib/shared/exceptions/client_status_exceptions.dart
  app/lib/shared/shared_functions.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: bug

#176 Feat: add clear Cache menu
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/clear_cache.dart
Labels: enhancement

#169 Startup rework
  app/lib/client/client.dart
  app/lib/client/fetcher.dart
  app/lib/client/load_mode.dart
  app/lib/client/storage.dart
  app/lib/home_page.dart
  app/lib/main.dart
  app/lib/shared/apps.dart
  app/lib/shared/types/startup_app.dart
  app/lib/shared/whats_new.dart
  app/lib/startup.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/conversations/conversations.dart
  app/lib/view/login/setup_screen_page_view_models.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/load_mode.dart
  app/lib/view/settings/subsettings/start_apps.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: enhancement

#184 Fix #181: calculate weekday on push message correctly
  app/lib/background_service/service.dart
  app/lib/client/client_submodules/substitutions.dart
Labels: bug

#188 'selectedDestinationDrawer' has not been initialized
  app/lib/home_page.dart
Labels: bug
