Repository lanis-mobile/lanis, pull requests merged in 2024-01, with the labels that each got.

#101 Homework checkbox
  README.md
  app/lib/client/client.dart
  app/lib/main.dart
  app/lib/view/mein_unterricht/course_overview.dart
  fastlane/metadata/android/en-US/images/phoneScreenshots/01.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/02.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/03.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/04.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/05.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/06.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/07.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/08.png
  preview.mockup
  screenshots/Conversation_Details.png
  screenshots/Conversations_Overview.png
  screenshots/Screenshot_1702113982.png
  screenshots/Screenshot_1702114019.png
  screenshots/Screenshot_1702114051.png
  screenshots/Screenshot_1702114070.png
  screenshots/Screenshot_1702114093.png
  screenshots/Screenshot_1702114119.png
Labels: enhancement

#102 Fix notifications
  app/lib/background_service/service.dart
Labels: bug

#103 Add new color themes
  README.md
  app/lib/client/client.dart
  app/lib/main.dart
  app/lib/themes.dart
  app/lib/themes/dark_theme.dart
  app/lib/themes/light_theme.dart
  app/lib/view/conversations/detailed_conversation.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/subsettings/theme_changer.dart
  app/pubspec.lock
  app/pubspec.yaml
  fastlane/metadata/android/en-US/images/phoneScreenshots/01.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/02.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/03.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/04.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/05.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/06.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/07.png
  preview.mockup
Labels: enhancement

#104 Fix not loading school theme on startup
  app/lib/themes.dart
Labels: bug

#105 add link to moodle login page
  app/lib/main.dart
Labels: enhancement

#106 Cleanup color theme code
  app/lib/client/client.dart
  app/lib/main.dart
  app/lib/themes.dart
  app/lib/view/settings/subsettings/theme_changer.dart
Labels: enhancement

#108 whats-new screen on app startup
  app/lib/client/client.dart
  app/lib/main.dart
  app/lib/shared/whats-new/whats_new.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#109 Generelle (Hot-)fixes
  app/lib/client/client.dart
  app/lib/main.dart
  app/lib/shared/whats_new.dart
  app/lib/view/conversations/detailed_conversation.dart
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: bug

#124 Feat: Add weekday and badge with count to substitutions tab
  app/lib/view/vertretungsplan/vertretungsplan.dart
Labels: enhancement

#125 Fix: url_launcher on special URI's
  app/android/app/src/main/AndroidManifest.xml
Labels: bug

#122 Fix: user is not logged in automatic after session expiration.
  app/lib/client/fetcher.dart
Labels: bug

#129 sort and filter "Aktuelles" on "Mein Unterricht"
  app/lib/client/client.dart
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/mein_unterricht/mein_unterricht.dart
Labels: enhancement

#137 Modify substitutions widget to enable overflow title
  app/lib/shared/marquee.dart
  app/lib/view/vertretungsplan/substitutionWidget.dart
Labels: bug, enhancement

#139 Reguläre Ausdrücke optimieren
  app/lib/client/client.dart
  app/lib/view/calendar/calendar.dart
  app/lib/view/login/auth.dart
  app/lib/view/login/screen.dart
Labels: low priority

#147 Update App icon
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/drawable-mdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/drawable-xhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/drawable-xxhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
Labels: enhancement

#149 Fix school colour
  app/lib/themes.dart
  app/lib/view/settings/subsettings/theme_changer.dart
Labels: bug

#110 Dateien hochladen und löschen bei Mein Unterricht
  app/lib/client/client.dart
  app/lib/shared/format_text.dart
  app/lib/shared/types/upload.dart
  app/lib/view/mein_unterricht/course_overview.dart
  app/lib/view/mein_unterricht/upload_page.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement
