Repository lanis-mobile/lanis, pull requests merged in 2024-12, with the labels that each got.

#314 Anpassung der Readme
  README.md
Labels: documentation

#310 Fix disappearing search bar
  app/lib/applets/conversations/view/conversations_view.dart
Labels: bug

#319 Fixes and small UX improvements
  app/lib/applets/data_storage/data_storage_root_view.dart
  app/lib/applets/data_storage/node_view.dart
  app/lib/applets/timetable/student/student_timetable_view.dart
  app/lib/home_page.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/startup.dart
  app/lib/themes.dart
  app/lib/view/login/school_selector.dart
Labels: bug, enhancement

#315 Use native_dio_adapter
  app/build.sh
  app/lib/core/connection_checker.dart
  app/lib/core/native_adapter_instance.dart
  app/lib/core/sph/session.dart
  app/lib/main.dart
  app/lib/view/login/school_selector.dart
  app/pubspec.yaml
Labels: enhancement

#320 Moddle Login with Dio
  app/lib/applets/data_storage/file_listtile.dart
  app/lib/applets/lessons/student/course_overview.dart
  app/lib/applets/lessons/student/parser.dart
  app/lib/models/lessons.dart
  app/lib/utils/file_operations.dart
  app/lib/view/moodle.dart
  app/pubspec.yaml
Labels: enhancement

#324 Faster startup
  app/lib/home_page.dart
  app/lib/main.dart
  app/lib/startup.dart
  app/lib/utils/authentication_state.dart
  app/lib/view/account_switcher/account_list_tile.dart
  app/lib/view/account_switcher/account_switcher.dart
  app/lib/view/login/auth.dart
  app/lib/view/moodle.dart
Labels: enhancement

#325 Redesign settings
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/main.dart
  app/lib/themes.dart
  app/lib/utils/callout.dart
  app/lib/utils/large_appbar.dart
  app/lib/utils/press_tile.dart
  app/lib/utils/radio_pills.dart
  app/lib/utils/slider_tile.dart
  app/lib/utils/switch_tile.dart
  app/lib/view/login/screen.dart
  app/lib/view/moodle.dart
  app/lib/view/settings/info_button.dart
  app/lib/view/settings/settings.dart
  app/lib/view/settings/settings_page_builder.dart
  app/lib/view/settings/subsettings/about.dart
  app/lib/view/settings/subsettings/appearance.dart
  app/lib/view/settings/subsettings/cache.dart
  app/lib/view/settings/subsettings/notifications.dart
  app/lib/view/settings/subsettings/theme_changer.dart
  app/lib/view/settings/subsettings/userdata.dart
Labels: enhancement

#328 Move the appbar definition to applets in order to support IconButtons
  app/lib/applets/calendar/calendar_view.dart
  app/lib/applets/calendar/definition.dart
  app/lib/applets/conversations/definition.dart
  app/lib/applets/conversations/view/conversations_view.dart
  app/lib/applets/data_storage/definition.dart
  app/lib/applets/definitions.dart
  app/lib/applets/lessons/definition.dart
  app/lib/applets/lessons/student/lessons_student_view.dart
  app/lib/applets/lessons/teacher/lessons_teacher_view.dart
  app/lib/applets/substitutions/definition.dart
  app/lib/applets/substitutions/parser.dart
  app/lib/applets/substitutions/substitutions_view.dart
  app/lib/applets/timetable/definition.dart
  app/lib/applets/timetable/student/student_timetable_view.dart
  app/lib/home_page.dart
  app/lib/widgets/offline_available_applets_section.dart
Labels: enhancement
