Repository lanis-mobile/lanis, pull requests merged in 2025-02, with the labels that each got.

#363 Update Native Android dependencies
  app/android/app/build.gradle
  app/android/app/src/main/kotlin/com/example/app/MainActivity.kt
  app/android/gradle.properties
  app/android/gradle/wrapper/gradle-wrapper.properties
  app/android/settings.gradle
Labels: dependencies

#357 Customizable Timetable
  app/lib/applets/timetable/student/parser.dart
  app/lib/applets/timetable/student/student_timetable_settings.dart
  app/lib/applets/timetable/student/student_timetable_view.dart
  app/lib/generated/intl/messages_de.dart
  app/lib/generated/intl/messages_en.dart
  app/lib/generated/l10n.dart
  app/lib/l10n/intl_de.arb
  app/lib/l10n/intl_en.arb
  app/lib/models/timetable.dart
  app/lib/view/settings/settings.dart
  app/pubspec.yaml
Labels: enhancement

#390 Fix applet access for parents
  app/lib/applets/lessons/definition.dart
  app/lib/applets/substitutions/definition.dart
Labels: bug, parent
