Repository lanis-mobile/lanis, pull requests merged in 2025-01, with the labels that each got.

#330 Fixed & improved amoled theme
  app/lib/applets/conversations/view/conversations_view.dart
  app/lib/main.dart
  app/lib/themes.dart
Labels: bug, enhancement

#332 optimize notification schedule for more battery and data efficiency
  app/lib/applets/conversations/background.dart
  app/lib/applets/conversations/definition.dart
  app/lib/applets/lessons/background.dart
  app/lib/applets/lessons/definition.dart
  app/lib/applets/substitutions/background.dart
  app/lib/background_service.dart
  app/lib/core/database/account_database/account_db.dart
  app/lib/core/database/account_database/kv_defaults.dart
  app/lib/core/sph/session.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/utils/range_slider_tile.dart
  app/lib/utils/slider_tile.dart
  app/lib/view/settings/subsettings/about.dart
  app/lib/view/settings/subsettings/notifications.dart
Labels: enhancement

#333 Properly disable background service options in settings
  app/lib/view/settings/subsettings/notifications.dart
Labels: bug

#334 331 lessons support for teachers
  app/lib/applets/lessons/definition.dart
  app/lib/applets/lessons/student/upload_page.dart
  app/lib/applets/lessons/teacher/course_detail_view/course_create_new_entry.dart
  app/lib/applets/lessons/teacher/course_detail_view/course_detail_view.dart
  app/lib/applets/lessons/teacher/lessons_teacher_view.dart
  app/lib/applets/lessons/teacher/parser.dart
  app/lib/applets/lessons/teacher/widgets/course_folder_card.dart
  app/lib/applets/lessons/teacher/widgets/course_folder_history_entry_card.dart
  app/lib/applets/lessons/teacher/widgets/course_folder_history_entry_file_chip.dart
  app/lib/applets/lessons/teacher/widgets/line_constraint_text.dart
  app/lib/applets/lessons/teacher/widgets/right_bottom_card_button.dart
  app/lib/applets/lessons/teacher/widgets/upload_file_to_course_chip.dart
  app/lib/applets/study_groups/student/student_exams_view.dart
  app/lib/applets/substitutions/parser.dart
  app/lib/core/sph/session.dart
  app/lib/models/lessons_teacher.dart
Labels: enhancement, teacher

#342 Fix & Improve comments on grades / marks
  app/lib/applets/lessons/student/course_overview.dart
  app/lib/applets/lessons/student/parser.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
Labels: bug, enhancement, student

#348 Account recovery on server side password change/account deletion
  app/lib/core/database/account_database/account_db.dart
  app/lib/home_page.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/startup.dart
  app/lib/view/login/auth.dart
  app/lib/widgets/reset_account_page.dart
Labels: bug, enhancement

#360 Calendar colors
  app/lib/applets/calendar/calendar_view.dart
  app/lib/applets/calendar/parser.dart
  app/lib/models/calendar_event.dart
Labels: enhancement

#361 Better release notes
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/utils/whats_new.dart
  app/lib/view/settings/settings.dart
Labels: enhancement
