Repository lanis-mobile/lanis, pull requests merged in 2025-06, with the labels that each got.

#420 feat: add debug export functionality and enhance file handling
  app/lib/applets/data_storage/file_listtile.dart
  app/lib/applets/lessons/student/course_overview.dart
  app/lib/utils/file_operations.dart
  app/lib/utils/logger.dart
  app/lib/view/settings/subsettings/about.dart
  app/lib/view/settings/subsettings/debug_export.dart
  app/pubspec.yaml
Labels: enhancement, datenschutz

#376 Overhaul of the file upload methods for lessons
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/kotlin/com/example/app/AppScanActivity.kt
  app/android/app/src/main/kotlin/com/example/app/MainActivity.kt
  app/android/app/src/main/res/drawable/rounded_arrow_left_alt_24.xml
  app/android/app/src/main/res/drawable/rounded_arrow_right_alt_24.xml
  app/android/app/src/main/res/layout/app_scan_activity_layout.xml
  app/android/app/src/main/res/values-de-rDE/strings.xml
  app/android/app/src/main/res/values/strings.xml
  app/android/build.gradle
  app/android/gradle.properties
  app/android/settings.gradle
  app/build.sh
  app/ios/Podfile.lock
  app/ios/Runner/AppDelegate.swift
  app/lib/applets/lessons/student/upload_page.dart
  app/lib/applets/lessons/teacher/widgets/upload_file_to_course_chip.dart
  app/lib/l10n/intl_de.arb
  app/lib/l10n/intl_en.arb
  app/lib/themes.dart
  app/lib/utils/file_operations.dart
  app/lib/utils/file_picker.dart
  app/lib/utils/random.dart
  app/pubspec.yaml
Labels: enhancement

#424 Don't check for updates if not from com.google.vending
  app/lib/utils/whats_new.dart
Labels: bug
